title: George H. W. Bush Composite Squadron Civil Air Patrol
header_1: George H. W. Bush Composite Squadron
header_2: Texas Wing Civil Air Patrol
menu_title: SWR-TX-041
email: info@tx041cap.org
phone_number: (979) 599-9038
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: tx041cap
facebook_username: tx041cap

# Meeting Information for Contact Page

meeting_location: Coulter Airfield (KCFD)
meeting_address: 6120 State Highway 21 East
meeting_city: Bryan
meeting_state: TX
meeting_zip: 77808
meeting_latitude: 30.718695
meeting_longitude: -96.337056
meeting_map_zoom: 15
meeting_schedule: >
  The George H. W. Bush Composite Squadron meets every Tuesday from 6:30pm (cadets) 
  or 7:00pm (seniors) until 9:00pm.  Special training events are frequently scheduled 
  on weekends.  Our Tuesday meeting locations vary as shown below.
meeting_location_description: >
  Portable Building in FBO Parking Lot of <a href="http://www.bryantx.gov/coulterairfield">Coulter Airfield</a> 
  in Bryan, Texas.
gmap_api_key: AIzaSyAxqX6BpSB7aipaJiSqbHtDCNeko7sKTdM

# Command Staff Info for Contact Page

cc_name: Maj Wendi Lamphear
cc_email: wlamphear@tx041cap.org

cds_name: Capt Forest Allen
cds_email: fallentx@gmail.com

cdc_name: 2d Lt Jessica Strominger
cdc_email: j.strominger94@gmail.com

# Navigation Menu Items
nav_menu_items:
  - About
  - Missions
  - Calendar
  - Resources
  - FAQs
  - Join
  - Contact

nav_menu_about:
  - Staff

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock